version: '3'

services:
  test_db:
    image: 'bitnami/mariadb:10.2.32'
    ports:
      - "3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_db
      - MARIADB_PASSWORD=my_pass
    volumes:
      - ./docker/db-data:/bitnami/mariadb
    networks:
      - test_network

  test_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_HOST=test_db
      - DB_USERNAME=my_user
      - DB_DATABASE=my_db
      - DB_PASSWORD=my_pass
      - LOG_CHANNEL=single
      - PHP_MODULES_DISABLE=opcache
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis
      - BROADCAST_DRIVER=redis
    depends_on:
      - test_db
    privileged: true
    ports:
      - 80:3000
    volumes:
      - ./:/app
    networks:
      - test_network

  redis:
    image: 'redis'
    ports:
      - 6379:6379
    networks:
      - test_network

  adminer_container:
      image: adminer:latest
      environment:
          ADMINER_DEFAULT_SERVER: test_db
          ADMINER_DESIGN: galkaev
      ports:
          - 8080:8080
      networks:
          - test_network

  echoserver_container:
      image: 'oanhnn/laravel-echo-server'
      volumes:
          - ./:/app
      environment:
          - LARAVEL_ECHO_SERVER_AUTH_HOST=test_app
          - LARAVEL_ECHO_SERVER_REDIS_HOST=redis
      ports:
          - 6001:6001
      networks:
          - test_network


networks:
  test_network:
    driver: bridge
